### ISSUE TITLE
Window bar is displayed when using sway (Wayland) but not with i3

### ISSUE THREAD

**Issue by dylandforbes** [thestinger/termite#388] opened 2016-08-11 22:55 UTC
I'm sorry if this is the wrong place for this, but I couldn't find anyting about this online. I thought you could point me in the right direction.
Here's what I see:
![out](https://cloud.githubusercontent.com/assets/19354224/17607628/c9ff935c-5fdb-11e6-898c-664dc7a3ccd2.png)
It doesn't happen with any other programs. Do you know what might be causing this?

Thanks so much.

**Comment by jelly** [comment] 2016-08-13 19:31
Thanks some answers from @Earnestly on irc, this issue is because of Client side decorations. Which can't be nicely fixed in termite (unless messing with private members)

Try GTK_CSD=1.

**Comment by Earnestly** [comment] 2016-08-13 22:45
The `GTK_CSD` environment isn't exposed in the standard GTK3 codebase, it's guarded against behind a few `#ifdef`'s.

```diff
--- a/gtk/gtkwindow.c
+++ b/gtk/gtkwindow.c
@@ -6025,9 +6025,6 @@
   GtkWindowPrivate *priv = window->priv;
   const gchar *csd_env;

-  if (priv->csd_requested)
-    return TRUE;
-
   if (!priv->decorated)
     return FALSE;

@@ -6035,28 +6032,6 @@
     return FALSE;

   csd_env = g_getenv ("GTK_CSD");
-
-#ifdef GDK_WINDOWING_BROADWAY
-  if (GDK_IS_BROADWAY_DISPLAY (gtk_widget_get_display (GTK_WIDGET (window))))
-    return TRUE;
-#endif
-
-#ifdef GDK_WINDOWING_WAYLAND
-  if (GDK_IS_WAYLAND_DISPLAY (gtk_widget_get_display (GTK_WIDGET (window))))
-    return TRUE;
-#endif
-
-#ifdef GDK_WINDOWING_MIR
-  if (GDK_IS_MIR_DISPLAY (gtk_widget_get_display (GTK_WIDGET (window))))
-    return TRUE;
-#endif
-
-#ifdef GDK_WINDOWING_WIN32
-  if (g_strcmp0 (csd_env, "0") != 0 &&
-      GDK_IS_WIN32_DISPLAY (gtk_widget_get_display (GTK_WIDGET (window))))
-    return TRUE;
-#endif
-
   return (g_strcmp0 (csd_env, "1") == 0);
 }

```

**Comment by dylandforbes** [comment] 2016-08-14 01:08
Wait so what are you saying I should do? I'm not at all familiar with the GTK codebase, or termite's for that matter.

**Comment by Earnestly** [comment] 2016-08-14 03:09
@dylandforbes It's more of a reply to @jelly.  The point is, unless you're willing to patch GTK3, these CSDs are here to stay unfortunately.  I'm not sure if termite can request them to not be displayed by claiming it is already decorated given that it seems to be refering to `priv`ate windows.

**Comment by thestinger** [comment] 2016-08-14 03:11
I consider this out-of-scope even if it can be worked around. I doubt you want title bars for other GTK+ applications either. You're asking the wrong people for a solution.

**Closed by thestinger** 2016-08-14 03:11 UTC

**Comment by embik** [comment] 2016-08-14 08:44
Just FYI, there is a pull request that fixes this: #276. I'm a bit sad that this won't be included with termite upstream, but I understand the decision. If you're using Gentoo, you can use/steal [my ebuild](https://github.com/embik/gentoo-overlay/tree/master/x11-terms/termite) that applies the patch. Works like a charm in sway.

**Comment by Snorflake** [comment] 2017-05-14 16:47
This bug still exists

**Comment by thestinger** [comment] 2018-01-27 20:33
The proper fix: https://git.gnome.org/browse/gtk+/commit/?h=gtk-3-22&id=f2adaba237519642b88ccb42b47a95cf539a2a12.

It's not a bug. It was a missing GTK feature.
