### ISSUE TITLE
Cursor rendering issues in vim

### ISSUE THREAD

**Issue by impo** [thestinger/termite#325] opened 2016-03-26 20:25 UTC
If I cause the cursor to jump in vim (or anywhere else) while the cursor is still solid, the cursor remains solid in its original position whilst correctly jumping to the new position.

I can cause termite to misrender this multiple times.

[Here's a screenshot of the issue.](http://i.imgur.com/emAc1tU.png)
[Here is my termite config.](http://pastebin.com/YB2qCSbd)

EDIT: Disabling vim-airline fixes the issue, although I'd like to have the best of both worlds. What's going on here?

**Comment by RaitoBezarius** [comment] 2016-03-27 01:19
I confirm to have the same issue. (termite config same except that I just have a font declaration, no colorscheme).

I was on tmux, I tried to use it w/o tmux, with tmux, with NeoVim, w/o NeoVim. And yeah, w/o vim-airline, it works.

**Comment by jelly** [comment] 2016-03-27 10:46
I have the feeling vte 0.44 causes this. Since it should be ABI compatible with the previous release you can try and downgrade your vte3-ng to the previous version and report back if it's still broken.

That said, it's probably an VTE bug

**Comment by dkasak** [comment] 2016-03-27 17:49
I'm encountering a different cursor rendering issue which I feel is probably related: when I enter termite command mode, moving the cursor does not re-render it in the new position and it seems to stay in place until I switch to a different workspace and then back again (using xmonad). This issue is resolved by downgrading to vte3-ng 0.42.4.a-1 (on Arch Linux).

**Comment by thestinger** [comment] 2016-03-29 04:20
Confirmed as an upstream problem in VTE 0.44. You can use the vte3-ng 0.42.4.a release as a workaround for now. It needs to be fixed upstream.

**Closed by thestinger** 2016-03-29 04:20 UTC
Labels: bug, upstream

**Comment by beanaroo** [comment] 2016-03-30 09:15
Just to confirm a fix has been implemented [upstream](https://bugzilla.gnome.org/show_bug.cgi?id=764299)
