### ISSUE TITLE
% (percent) symbol appears in upper left corner of small terminals when rapid prompt enabled in zsh

### ISSUE THREAD

**Issue by kylebarbour** [thestinger/termite#748] opened 2020-07-14 15:40 UTC
When I open small windows, a black-on-white percent symbol (see below) appears in the upper left corner. I notice this in conjunction with the rapid prompt options of `zsh` and [`powerlevel10k`](https://github.com/romkatv/powerlevel10k) with minimal configuration settings, but can occur with `zsh` alone. Initially, I reported this against `powerlevel10k` (see romkatv/powerlevel10k/issues/887), but the maintainer was kind enough to [clarify that the problem is in the terminal](https://github.com/romkatv/powerlevel10k/issues/887#issuecomment-657982268).

![Percent in corner](https://user-images.githubusercontent.com/4647176/87363005-353c2600-c53e-11ea-928f-8d8eca97226c.png)

I can verify that this occurs simultaneously with the terminal incorrectly reporting the starting dimensions as seen by putting `stty size` or `typeset -p LINES COLUMNS` at the top of `.zshrc` as suggested by the `powerlevel10k` maintainer. He suggested that this might be a results of a buggy VTE implementation, but that's past my personal knowledge.

System:
```
$ uname -srv
Linux 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000
```

Window manager:
```
$ bspwm -v
0.9.7-10-g2ffd9c1
$ pacman -Qe | grep -e bspwm
bspwm 0.9.9-2
```

Terminal:
```
$ termite -v
termite v15
$ pacman -Qe | grep -e termite
termite 15-2
```

I installed `termite` using the [standard Arch Linux repository](https://www.archlinux.org/packages/community/x86_64/termite/) via `pacman -S`.

Thank you for your software!

**Comment by jfernandz** [comment] 2020-08-11 10:41
I think this is a duplicate of https://github.com/thestinger/termite/issues/741

**Comment by jessdot** [comment] 2020-09-21 03:14
You should try to comment this lines in your zshrc, it's works for me..

![image](https://user-images.githubusercontent.com/67190199/93729792-fd7fd900-fb93-11ea-8d39-770a398e7459.png)

Write changes and close terminal, when open new instance only appears the prompt without % (percent) symbol

**Comment by kylebarbour** [comment] 2020-09-23 18:43
@jessdot Of course; the bug report is against this occuring with transient prompt enabled.

**Comment by thestinger** [comment] 2021-05-07 11:52
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Closed by thestinger** 2021-05-07 11:52 UTC
