### ISSUE TITLE
Allow for customizable keyboard shortcuts

### ISSUE THREAD

**Issue by apetresc** [thestinger/termite#488] opened 2017-06-13 15:19 UTC
Some of Termite's default keyboard shortcuts in insert mode conflict with various tools like vim (namely `Ctrl-Tab` for scrollback completion for me, but I'm sure others have their own) . As these sorts of things are typically deeply-engrained in people's muscle memories, I think it's reasonable to expect the terminal emulator to allow these to be reconfigured.

**Comment by jelly** [comment] 2017-06-17 17:33
This is a duplicate of 'custom keyboard binds #62'

**Closed by jelly** 2017-06-17 17:33 UTC
