### ISSUE TITLE
hide title bar

### ISSUE THREAD

**Issue by mathroc** [thestinger/termite#575] opened 2018-02-27 20:51 UTC
Hi,

sorry if I'm asking for something abvious but i didn't find in the config file how I can hide the title bar. I'm running termine inside sway and I have two title bar, the sway adds to every window and one drawn by termite (the gray bar with the tile and a close button). I'd like to have only the sway one because the other one does not work well in tabbed mode and and have a very different look and feel than the rest of the system

thank you

**Comment by Narrat** [comment] 2018-03-01 00:27
IIRC there were some issues reported for this in the past.
In short: GTK is doing this as they switched to CSD (Client Side Decorations) some major versions ago. Especially noticeable on Wayland compositors.
Recently they added support for [KDEs SSD](https://www.reddit.com/r/linux/comments/791qle/gtk_adds_support_for_kdes_serverside_decorations/) which may tone the issue down.

**Comment by jelly** [comment] 2018-05-18 13:41
Duplicate of #276

**Closed by jelly** 2018-05-18 13:41 UTC
