### ISSUE TITLE
termite coredumps when using vim/less and when font is increased

### ISSUE THREAD

**Issue by diegoviola** [thestinger/termite#312] opened 2016-02-21 02:38 UTC
termite coredumps for me when using a program like `vim` or `less`, here is how I can reproduce this:

1. open vim or less
2. type colon, i.e. `:`
3. increase the font with Shift+Control+Space and ++ then press Enter.

At this point termite crash for me with this error message:

```
**
Vte:ERROR:ring.cc:394:void _vte_ring_thaw_one_row(VteRing*): assertion failed: (ring->start < ring->writable)
Aborted (core dumped)
```

I'm on Arch Linux (x86-64)
termite v11

**Comment by polyzen** [comment] 2016-02-21 02:41
@diegoviola, perhaps this is a dupe of #194?

**Comment by diegoviola** [comment] 2016-02-21 02:46
I think so.

**Closed** 2016-02-21 03:12 UTC
