### ISSUE TITLE
Image preview not working in ranger and w3m can't show them

### ISSUE THREAD

**Issue by Alkeryn** [thestinger/termite#501] opened 2017-07-13 04:35 UTC
That's about it here is an expample screenshot
![image](https://user-images.githubusercontent.com/11599075/28150542-63e6495e-6795-11e7-8588-0f8d26133a2b.png)
I don't have this issue on urxvt but i prefer termite
please fix this :/
also the termite-ranger-fix from AUR didn't solved the issue

**Comment by jelly** [comment] 2017-07-13 07:38
Well your bugreport isn't really informative. Disregard that, I can't get the image preview working in rxvt and xterm with the suggestions in https://github.com/ranger/ranger/wiki/Image-Previews

To be honest the feature is really a hack in w3m.

**Comment by Alkeryn** [comment] 2017-07-22 17:02
Well i switched to urxvt in the end, sad since i love some of termite features but meh
that's like it ^^

**Comment by Iambecomeroot** [comment] 2017-07-31 18:25
Would it be possible to implement something like urxvt pixbuf?

**Comment by mrneilypops** [comment] 2017-08-15 11:23
It would be great to get ranger image preview working in termite. I am loving termite but still have to use urxvt for ranger...

**Comment by jelly** [comment] 2017-08-15 11:51
@mrneilypops sure, I have no idea what the limitation is however and it does not work for me in urxvt.

**Comment by teto** [comment] 2017-10-26 09:26
I use termite and ranger preview works just fine (even got video preview working)

**Comment by oblitum** [comment] 2017-12-08 15:23
I'm getting just "list index out of range" while browsing and with `w3m` installed/image previews enabled. `w3m` works fine when executed for image preview.

**Comment by oblitum** [comment] 2017-12-08 15:56
Hmm, nevermind, w3m is just opening an external imagemagick X gui no matter what I do, and if I open a web page it doesn't preview images in the terminal at all. Not sure how people get this working.

**Comment by oblitum** [comment] 2017-12-08 15:57
@teto can you please tell what you do to make it work? I'm on ArchLinux, and as I said above, it simply doesn't.

**Comment by teto** [comment] 2018-01-18 13:34
I don't remember doing anything extraordinary, my ranger config is https://github.com/teto/home/blob/master/config/ranger/rc.conf, just set imagepreview. w3m needs to be in path with some access to fbcon. Maybe you need to check w3m version ? maybe there is some compilation time flag. You should try to see images with w3m first before trying with ranger. Note that the preview is not always perfect, sometimes some colors are off etc.

**Comment by wulvyrn** [comment] 2018-01-18 21:39
The default ranger file has this line which isn't in your rc.vonf file:
```
set preview_image_method w3m.
```

I'm also using termite with ranger on sway with this issue.

**Comment by 1094** [comment] 2018-03-29 17:31
I am using i3 4.15.0.1 with termite v13, ranger 1.9.1, and w3m 0.5.3, with the following in my rc.conf:
```
set preview_script ~/.config/ranger/scope.sh  
set use_preview_script true  
set preview_images_method w3m 
``` 
The previews do not show on default, I have to use `zi`.

![thu-00](https://user-images.githubusercontent.com/31363848/38103544-9270ca7a-3354-11e8-8e5e-6ae61a9f70de.png)
![thu-15](https://user-images.githubusercontent.com/31363848/38103580-b598f400-3354-11e8-8491-44e39c076941.png)

The only problem I'm having is that some of the previews break my termite background color which I am assuming is related to the ranger/w3m transparency issue).

**Comment by oblitum** [comment] 2018-03-31 03:19
Hey! Exactly like @1094, it's working now for me too. It doesn't work inside TMUX. Also, I'm getting the same transparency issues.

**Comment by Alkeryn** [comment] 2018-04-02 20:00
Oh sorry didn't saw it followed well i use urxvt for ranger
here is my rc.conf and my .Xressource
rc.conf
`
# ===================================================================
# This file contains the default startup commands for ranger.
# To change them, it is recommended to create the file
# ~/.config/ranger/rc.conf and add your custom commands there.
#
# If you copy this whole file there, you may want to set the environment
# variable RANGER_LOAD_DEFAULT_RC to FALSE to avoid loading it twice.
#
# The purpose of this file is mainly to define keybindings and settings.
# For running more complex python code, please create a plugin in "plugins/" or
# a command in "commands.py".
#
# Each line is a command that will be run before the user interface
# is initialized.  As a result, you can not use commands which rely
# on the UI such as :delete or :mark.
# ===================================================================

# ===================================================================
# == Options
# ===================================================================

# Which viewmode should be used?  Possible values are:
#     miller: Use miller columns which show multiple levels of the hierarchy
#     multipane: Midnight-commander like multipane view showing all tabs next
#                to each other
set viewmode miller
#set viewmode multipane

# How many columns are there, and what are their relative widths?
set column_ratios 1,3,4

# Which files should be hidden? (regular expression)
set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$

# Show hidden files? You can toggle this by typing 'zh'
set show_hidden false

# Ask for a confirmation when running the "delete" command?
# Valid values are "always", "never", "multiple" (default)
# With "multiple", ranger will ask only if you delete multiple files at once.
set confirm_on_delete multiple

# Which script is used to generate file previews?
# ranger ships with scope.sh, a script that calls external programs (see
# README.md for dependencies) to preview images, archives, etc.
set preview_script ~/.config/ranger/scope.sh

# Use the external preview script or display simple plain text or image previews?
set use_preview_script true

# Automatically count files in the directory, even before entering them?
set automatically_count_files true

# Open all images in this directory when running certain image viewers
# like feh or sxiv?  You can still open selected files by marking them.
set open_all_images true

# Be aware of version control systems and display information.
set vcs_aware false

# State of the three backends git, hg, bzr. The possible states are
# disabled, local (only show local info), enabled (show local and remote
# information).
set vcs_backend_git enabled
set vcs_backend_hg disabled
set vcs_backend_bzr disabled

# Use one of the supported image preview protocols
set preview_images true

# Set the preview image method. Supported methods:
#
# * w3m (default):
#   Preview images in full color with the external command "w3mimgpreview"?
#   This requires the console web browser "w3m" and a supported terminal.
#   It has been successfully tested with "xterm" and "urxvt" without tmux.
#
# * iterm2:
#   Preview images in full color using iTerm2 image previews
#   (http://iterm2.com/images.html). This requires using iTerm2 compiled
#   with image preview support.
#
# * urxvt:
#   Preview images in full color using urxvt image backgrounds. This
#   requires using urxvt compiled with pixbuf support.
#
# * urxvt-full:
#   The same as urxvt but utilizing not only the preview pane but the
#   whole terminal window.
set preview_images_method w3m

# Use a unicode "..." character to mark cut-off filenames?
set unicode_ellipsis false

# Show dotfiles in the bookmark preview box?
set show_hidden_bookmarks true

# Which colorscheme to use?  These colorschemes are available by default:
# default, jungle, snow, solarized
set colorscheme default

# Preview files on the rightmost column?
# And collapse (shrink) the last column if there is nothing to preview?
set preview_files true
set preview_directories true
set collapse_preview true

# Save the console history on exit?
set save_console_history true

# Draw the status bar on top of the browser window (default: bottom)
set status_bar_on_top false

# Draw a progress bar in the status bar which displays the average state of all
# currently running tasks which support progress bars?
set draw_progress_bar_in_status_bar true

# Draw borders around columns?
set draw_borders false

# Display the directory name in tabs?
set dirname_in_tabs false

# Enable the mouse support?
set mouse_enabled true

# Display the file size in the main column or status bar?
set display_size_in_main_column true
set display_size_in_status_bar true

# Display files tags in all columns or only in main column?
set display_tags_in_all_columns true

# Set a title for the window?
set update_title false

# Set the title to "ranger" in the tmux program?
set update_tmux_title false

# Shorten the title if it gets long?  The number defines how many
# directories are displayed at once, 0 turns off this feature.
set shorten_title 3

# Abbreviate $HOME with ~ in the titlebar (first line) of ranger?
set tilde_in_titlebar false

# How many directory-changes or console-commands should be kept in history?
set max_history_size 20
set max_console_history_size 50

# Try to keep so much space between the top/bottom border when scrolling:
set scroll_offset 8

# Flush the input after each key hit?  (Noticeable when ranger lags)
set flushinput true

# Padding on the right when there's no preview?
# This allows you to click into the space to run the file.
set padding_right true

# Save bookmarks (used with mX and `X) instantly?
# This helps to synchronize bookmarks between multiple ranger
# instances but leads to *slight* performance loss.
# When false, bookmarks are saved when ranger is exited.
set autosave_bookmarks true

# You can display the "real" cumulative size of directories by using the
# command :get_cumulative_size or typing "dc".  The size is expensive to
# calculate and will not be updated automatically.  You can choose
# to update it automatically though by turning on this option:
set autoupdate_cumulative_size false

# Turning this on makes sense for screen readers:
set show_cursor false

# One of: size, natural, basename, atime, ctime, mtime, type, random
set sort natural

# Additional sorting options
set sort_reverse false
set sort_case_insensitive true
set sort_directories_first true
set sort_unicode false

# Enable this if key combinations with the Alt Key don't work for you.
# (Especially on xterm)
set xterm_alt_key false

# Whether to include bookmarks in cd command
set cd_bookmarks true

# Avoid previewing files larger than this size, in bytes.  Use a value of 0 to
# disable this feature.
set preview_max_size 0

# Add the highlighted file to the path in the titlebar
set show_selection_in_titlebar true

# The delay that ranger idly waits for user input, in milliseconds, with a
# resolution of 100ms.  Lower delay reduces lag between directory updates but
# increases CPU load.
set idle_delay 2000

# When the metadata manager module looks for metadata, should it only look for
# a ".metadata.json" file in the current directory, or do a deep search and
# check all directories above the current one as well?
set metadata_deep_search false

# Clear all existing filters when leaving a directory
set clear_filters_on_dir_change false

# Disable displaying line numbers in main column
set line_numbers false

# ===================================================================
# == Local Options
# ===================================================================
# You can set local options that only affect a single directory.

# Examples:
# setlocal path=~/downloads sort mtime

# ===================================================================
# == Command Aliases in the Console
# ===================================================================

alias e    edit
alias q    quit
alias q!   quitall
alias qa   quitall
alias qall quitall
alias setl setlocal

alias filter     scout -prt
alias find       scout -aeit
alias mark       scout -mr
alias unmark     scout -Mr
alias search     scout -rs
alias search_inc scout -rts
alias travel     scout -aefiklst

# ===================================================================
# == Define keys for the browser
# ===================================================================

# Basic
map     Q quit!
map     q quit
copymap q ZZ ZQ

map R     reload_cwd
map <C-r> reset
map <C-l> redraw_window
map <C-c> abort
map <esc> change_mode normal
map ~ set viewmode!

map i display_file
map ? help
map W display_log
map w taskview_open
map S shell $SHELL

map :  console
map ;  console
map !  console shell%space
map @  console -p6 shell  %%s
map #  console shell -p%space
map s  console shell%space
map r  chain draw_possible_programs; console open_with%%space
map f  console find%space
map cd console cd%space

# Change the line mode
map Mf linemode filename
map Mi linemode fileinfo
map Mm linemode mtime
map Mp linemode permissions
map Ms linemode sizemtime
map Mt linemode metatitle

# Tagging / Marking
map t       tag_toggle
map ut      tag_remove
map "<any>  tag_toggle tag=%any
map <Space> mark_files toggle=True
map v       mark_files all=True toggle=True
map uv      mark_files all=True val=False
map V       toggle_visual_mode
map uV      toggle_visual_mode reverse=True

# For the nostalgics: Midnight Commander bindings
map <F1> help
map <F3> display_file
map <F4> edit
map <F5> copy
map <F6> cut
map <F7> console mkdir%space
map <F8> console delete
map <F10> exit

# In case you work on a keyboard with dvorak layout
map <UP>       move up=1
map <DOWN>     move down=1
map <LEFT>     move left=1
map <RIGHT>    move right=1
map <HOME>     move to=0
map <END>      move to=-1
map <PAGEDOWN> move down=1   pages=True
map <PAGEUP>   move up=1     pages=True
map <CR>       move right=1
map <DELETE>   console delete
map <INSERT>   console touch%space

# VIM-like
copymap <UP>       k
copymap <DOWN>     j
copymap <LEFT>     h
copymap <RIGHT>    l
copymap <HOME>     gg
copymap <END>      G
copymap <PAGEDOWN> <C-F>
copymap <PAGEUP>   <C-B>

map J  move down=0.5  pages=True
map K  move up=0.5    pages=True
copymap J <C-D>
copymap K <C-U>

# Jumping around
map H     history_go -1
map L     history_go 1
map ]     move_parent 1
map [     move_parent -1
map }     traverse

map gh cd ~
map ge cd /etc
map gu cd /usr
map gd cd /dev
map gl cd -r .
map gL cd -r %f
map go cd /opt
map gv cd /var
map gm cd /media
map gM cd /mnt
map gs cd /srv
map gr cd /
map gR eval fm.cd(ranger.RANGERDIR)
map g/ cd /
map g? cd /usr/share/doc/ranger

# External Programs
map E  edit
map du shell -p du --max-depth=1 -h --apparent-size
map dU shell -p du --max-depth=1 -h --apparent-size | sort -rh
map yp shell -f echo -n %d/%f | xsel -i; xsel -o | xsel -i -b -p
map yd shell -f echo -n %d    | xsel -i; xsel -o | xsel -i -b -p
map yn shell -f echo -n %f    | xsel -i; xsel -o | xsel -i -b -p

# Filesystem Operations
map =  chmod

map cw console rename%space
map cv bulkrename
map a  rename_append
map A  eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"))
map I  eval fm.open_console('rename ' + fm.thisfile.relative_path.replace("%", "%%"), position=7)

map pp paste
map po paste overwrite=True
map pP paste append=True
map pO paste overwrite=True append=True
map pl paste_symlink relative=False
map pL paste_symlink relative=True
map phl paste_hardlink
map pht paste_hardlinked_subtree

map dD console delete

map dd cut
map ud uncut
map da cut mode=add
map dr cut mode=remove
map dt cut mode=toggle
map df flat 1

map yy copy
map uy uncut
map ya copy mode=add
map yr copy mode=remove
map yt copy mode=toggle

# Temporary workarounds
map dgg eval fm.cut(dirarg=dict(to=0), narg=quantifier)
map dG  eval fm.cut(dirarg=dict(to=-1), narg=quantifier)
map dj  eval fm.cut(dirarg=dict(down=1), narg=quantifier)
map dk  eval fm.cut(dirarg=dict(up=1), narg=quantifier)
map ygg eval fm.copy(dirarg=dict(to=0), narg=quantifier)
map yG  eval fm.copy(dirarg=dict(to=-1), narg=quantifier)
map yj  eval fm.copy(dirarg=dict(down=1), narg=quantifier)
map yk  eval fm.copy(dirarg=dict(up=1), narg=quantifier)

# Searching
map /  console search%space
map n  search_next
map N  search_next forward=False
map ct search_next order=tag
map cs search_next order=size
map ci search_next order=mimetype
map cc search_next order=ctime
map cm search_next order=mtime
map ca search_next order=atime

# Tabs
map <C-n>     tab_new ~
map <C-w>     tab_close
map <TAB>     tab_move 1
map <S-TAB>   tab_move -1
map <A-Right> tab_move 1
map <A-Left>  tab_move -1
map gt        tab_move 1
map gT        tab_move -1
map gn        tab_new ~
map gc        tab_close
map uq        tab_restore
map <a-1>     tab_open 1
map <a-2>     tab_open 2
map <a-3>     tab_open 3
map <a-4>     tab_open 4
map <a-5>     tab_open 5
map <a-6>     tab_open 6
map <a-7>     tab_open 7
map <a-8>     tab_open 8
map <a-9>     tab_open 9

# Sorting
map or set sort_reverse!
map oz set sort=random
map os chain set sort=size;      set sort_reverse=False
map ob chain set sort=basename;  set sort_reverse=False
map on chain set sort=natural;   set sort_reverse=False
map om chain set sort=mtime;     set sort_reverse=False
map oc chain set sort=ctime;     set sort_reverse=False
map oa chain set sort=atime;     set sort_reverse=False
map ot chain set sort=type;      set sort_reverse=False
map oe chain set sort=extension; set sort_reverse=False

map oS chain set sort=size;      set sort_reverse=True
map oB chain set sort=basename;  set sort_reverse=True
map oN chain set sort=natural;   set sort_reverse=True
map oM chain set sort=mtime;     set sort_reverse=True
map oC chain set sort=ctime;     set sort_reverse=True
map oA chain set sort=atime;     set sort_reverse=True
map oT chain set sort=type;      set sort_reverse=True
map oE chain set sort=extension; set sort_reverse=True

map dc get_cumulative_size

# Settings
map zc    set collapse_preview!
map zd    set sort_directories_first!
map zh    set show_hidden!
map <C-h> set show_hidden!
map zI    set flushinput!
map zi    set preview_images!
map zm    set mouse_enabled!
map zp    set preview_files!
map zP    set preview_directories!
map zs    set sort_case_insensitive!
map zu    set autoupdate_cumulative_size!
map zv    set use_preview_script!
map zf    console filter%space

# Bookmarks
map `<any>  enter_bookmark %any
map '<any>  enter_bookmark %any
map m<any>  set_bookmark %any
map um<any> unset_bookmark %any

map m<bg>   draw_bookmarks
copymap m<bg>  um<bg> `<bg> '<bg>

# Generate all the chmod bindings with some python help:
eval for arg in "rwxXst": cmd("map +u{0} shell -f chmod u+{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map +g{0} shell -f chmod g+{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map +o{0} shell -f chmod o+{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map +a{0} shell -f chmod a+{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map +{0}  shell -f chmod u+{0} %s".format(arg))

eval for arg in "rwxXst": cmd("map -u{0} shell -f chmod u-{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map -g{0} shell -f chmod g-{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map -o{0} shell -f chmod o-{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map -a{0} shell -f chmod a-{0} %s".format(arg))
eval for arg in "rwxXst": cmd("map -{0}  shell -f chmod u-{0} %s".format(arg))

# ===================================================================
# == Define keys for the console
# ===================================================================
# Note: Unmapped keys are passed directly to the console.

# Basic
cmap <tab>   eval fm.ui.console.tab()
cmap <s-tab> eval fm.ui.console.tab(-1)
cmap <ESC>   eval fm.ui.console.close()
cmap <CR>    eval fm.ui.console.execute()
cmap <C-l>   redraw_window

copycmap <ESC> <C-c>
copycmap <CR>  <C-j>

# Move around
cmap <up>    eval fm.ui.console.history_move(-1)
cmap <down>  eval fm.ui.console.history_move(1)
cmap <left>  eval fm.ui.console.move(left=1)
cmap <right> eval fm.ui.console.move(right=1)
cmap <home>  eval fm.ui.console.move(right=0, absolute=True)
cmap <end>   eval fm.ui.console.move(right=-1, absolute=True)
cmap <a-left>   eval fm.ui.console.move_word(left=1)
cmap <a-right>  eval fm.ui.console.move_word(right=1)

# Line Editing
cmap <backspace>  eval fm.ui.console.delete(-1)
cmap <delete>     eval fm.ui.console.delete(0)
cmap <C-w>        eval fm.ui.console.delete_word()
cmap <A-d>        eval fm.ui.console.delete_word(backward=False)
cmap <C-k>        eval fm.ui.console.delete_rest(1)
cmap <C-u>        eval fm.ui.console.delete_rest(-1)
cmap <C-y>        eval fm.ui.console.paste()

# And of course the emacs way
copycmap <up>        <C-p>
copycmap <down>      <C-n>
copycmap <left>      <C-b>
copycmap <right>     <C-f>
copycmap <home>      <C-a>
copycmap <end>       <C-e>
copycmap <delete>    <C-d>
copycmap <backspace> <C-h>

# Note: There are multiple ways to express backspaces.  <backspace> (code 263)
# and <backspace2> (code 127).  To be sure, use both.
copycmap <backspace> <backspace2>

# This special expression allows typing in numerals:
cmap <allow_quantifiers> false

# ===================================================================
# == Pager Keybindings
# ===================================================================

# Movement
pmap  <down>      pager_move  down=1
pmap  <up>        pager_move  up=1
pmap  <left>      pager_move  left=4
pmap  <right>     pager_move  right=4
pmap  <home>      pager_move  to=0
pmap  <end>       pager_move  to=-1
pmap  <pagedown>  pager_move  down=1.0  pages=True
pmap  <pageup>    pager_move  up=1.0    pages=True
pmap  <C-d>       pager_move  down=0.5  pages=True
pmap  <C-u>       pager_move  up=0.5    pages=True

copypmap <UP>       k  <C-p>
copypmap <DOWN>     j  <C-n> <CR>
copypmap <LEFT>     h
copypmap <RIGHT>    l
copypmap <HOME>     g
copypmap <END>      G
copypmap <C-d>      d
copypmap <C-u>      u
copypmap <PAGEDOWN> n  f  <C-F>  <Space>
copypmap <PAGEUP>   p  b  <C-B>

# Basic
pmap     <C-l> redraw_window
pmap     <ESC> pager_close
copypmap <ESC> q Q i <F3>
pmap E      edit_file

# ===================================================================
# == Taskview Keybindings
# ===================================================================

# Movement
tmap <up>        taskview_move up=1
tmap <down>      taskview_move down=1
tmap <home>      taskview_move to=0
tmap <end>       taskview_move to=-1
tmap <pagedown>  taskview_move down=1.0  pages=True
tmap <pageup>    taskview_move up=1.0    pages=True
tmap <C-d>       taskview_move down=0.5  pages=True
tmap <C-u>       taskview_move up=0.5    pages=True

copytmap <UP>       k  <C-p>
copytmap <DOWN>     j  <C-n> <CR>
copytmap <HOME>     g
copytmap <END>      G
copytmap <C-u>      u
copytmap <PAGEDOWN> n  f  <C-F>  <Space>
copytmap <PAGEUP>   p  b  <C-B>

# Changing priority and deleting tasks
tmap J          eval -q fm.ui.taskview.task_move(-1)
tmap K          eval -q fm.ui.taskview.task_move(0)
tmap dd         eval -q fm.ui.taskview.task_remove()
tmap <pagedown> eval -q fm.ui.taskview.task_move(-1)
tmap <pageup>   eval -q fm.ui.taskview.task_move(0)
tmap <delete>   eval -q fm.ui.taskview.task_remove()

# Basic
tmap <C-l> redraw_window
tmap <ESC> taskview_close
copytmap <ESC> q Q w <C-c>
`
.Xressource
`
urxvt.termName: rxvt-unicode-256color

urxvt.foreground: #ff0000
urxvt.background: [70]#000000
urxvt.depth: 32

urxvt.scrollBar: false
URxvt*borderLess: false
URxvt.cursorBlink: true
!URxvt.fading: 0

urxvt.font: xft:DejaVu Sans Mono:size=11
    xft:unifont:medium
urxvt.boldfont: xft:DejaVu Sans Mono:bold:size=11
URxvt.letterSpace: 0

urxvt.saveLines: 12000

urxvt.pointerColorBackground: [70]#000000
urxvt.pointerColorForeground: [70]#ff0000

urxvt.scrollstyle: rxvt

*color0: #073642
*color1: #dc322f
*color2: #859900
*color3: #b58900
*color4: #268bd2
*color5: #d33682
*color6: #2aa198
*color7: #eee8d5
*color8: #002b36
*color9: #cb4b16
*color10: #586e75
*color11: #657b83
*color12: #839496
*color13: #6c71c4
*color14: #93a1a1
*color15: #fdf6e3

urxvt.colorBD: #ff0000

!URxvt.cursorUnderline: false
!URxvt*hold: boolean
!URxvt.intensityStyles: false
!URxvt.perl-ext-common: default,matcher,clipboard,keyboard-select,selection_to_clipboard
URxvt.perl-ext-common: default,matcher,clipboard,keyboard-select
URxvt*urgentOnBell: false

! URLs
!

URxvt.matcher.rend.0: Uline Bold fg6
URxvt.keysym.Control-l: perl:matcher:last
URxvt.keysym.Control-u: perl:matcher:list

!
! Clickable URLs
!

URxvt.url-launcher: chromium
URxvt.matcher.button: 1

!
! Paste
!

URxvt.keysym.Shift-Control-V: perl:clipboard:paste
!URxvt.iso14755: False

!
! Fonts
!


!
! Select text with the keyboard
!

URxvt.keysym.M-Escape: perl:keyboard-select:activate

!
! Search text with keyboard
!

URxvt.keysym.M-s: perl:keyboard-select:search

!
! Fix for Home and End keys
!

URxvt.keysym.Home: \033[1~
URxvt.keysym.End: \033[4~
URxvt.keysym.KP_Home: \033[1~
URxvt.keysym.KP_End:  \033[4~

!
! Cursor theme
!

Xcursor.theme: Vanilla-DMZ


!
! Rofi
!

!rofi.color-enabled: true
!rofi.color-window: #002b36, #255662, #0d4350
!rofi.color-normal: #002b36, #839496, #002b36, #0d4350, #839496
!rofi.color-active: #0d4350, #2aa198, #002b36, #839496, #002B36
!rofi.color-urgent: #a83838, #ffffff, #eee8d5, #a83838, #ffffff
!rofi.monitor: 0
!rofi.font: xos4Terminus

!
! Colors
!

!#define S_yellow		#b58900
!#define S_orange		#cb4b16
!#define S_red			#dc322f
!#define S_magenta		#d33682
!#define S_violet		#6c71c4
!#define S_blue			#268bd2
!#define S_cyan			#2aa198
!#define S_green			#859900
!
!#define S_base03		#002b36
!#define S_base02		#0d4350
!#define S_base01		#586e75
!#define S_base00		#657b83
!#define S_base0			#839496
!#define S_base1			#93a1a1
!#define S_base2			#839496
!#define S_base3			#fdf6e3
!
!*fading:		0
!*fadeColor:		S_base03
!URxvt.cursorColor:	S_base1
!*pointerColorBackground:S_base01
!*pointerColorForeground:S_base1
!
!URxvt.color0:		S_base02
!URxvt.color1:		S_red
!URxvt.color2:		S_green
!URxvt.color3:		S_yellow
!URxvt.color4:		S_blue
!URxvt.color5:		S_magenta
!URxvt.color6:		S_cyan
!URxvt.color7:		S_base2
!URxvt.color9:		S_orange
!URxvt.color8:		S_base03
!URxvt.color10:		S_base01
!URxvt.color11:		S_base00
!URxvt.color12:		S_base0
!URxvt.color13:		S_violet
!URxvt.color14:		S_base1
!URxvt.color15:		S_base3
`

**Comment by SirWindfield** [comment] 2018-04-09 20:52
I am using termite and just set the image preview flag to true. The image is showing up when I select the image in the list.

**Comment by mhham** [comment] 2018-05-10 23:34
For me the image preview is working, but when I move to another item (say a text file), the whole background becomes transparent, except the area with text (cf. screenshot below)

![screenshot_ranger](https://user-images.githubusercontent.com/26010469/39899293-5f730b3c-54bb-11e8-9bea-b3acaf97a736.png)

**Comment by Alkeryn** [comment] 2018-05-18 16:13
@mhham What are your termite and ranger config ?
because it don't work like that for me

**Comment by mhham** [comment] 2018-05-20 01:40
@Alkeryn 

Here are my configs : 
- termite config: https://gist.github.com/mhham/2177b35555e727cc5cf2b6fa73f09fd8
- ranger rc.conf : https://gist.github.com/mhham/4d921a25dc03d3c17eedac4a49116daa

**Comment by freed00m** [comment] 2018-05-21 21:06
I use gnome-terminal without compositor and I notice it can draw over another apps, making it super annoying, HOW?.

![2018-05-21-230414_1920x1080_scrot](https://user-images.githubusercontent.com/9461698/40329884-6bc8fb9c-5d4b-11e8-91bd-50f907abd81e.png)

Sorry you had to look at my face so many times but the point remains.

**Comment by Alkeryn** [comment] 2018-05-30 10:16
Welp i found out what was the issue
it turns out it is due to bspwm
because it does work in termite + i3
but not on termite + bspwm
though it work on urxvt + bspwm 
so that's weird

**Comment by mhham** [comment] 2018-06-02 09:06
I am using termite + i3, so I guess this is not really the issue.

**Comment by Alkeryn** [comment] 2018-06-04 15:11
@mhham Did you read my comment ?, i explicitly said the issue was bspwm ^^

**Comment by Xarchuser** [comment] 2018-06-21 14:33
@Alkeryn did u find any solution? that issue happens when i use termite + bspwm  however urxvt it works well on bspwm, termite on another window manager works well too, it's odd...

**Comment by Xarchuser** [comment] 2018-06-21 14:37
look at that , urxvt vs termite on bspwm

![21-06-18_11 23 07](https://user-images.githubusercontent.com/29339012/41725832-2cb3fad8-7547-11e8-9cc7-5b6a0f6f64ff.png)

**Comment by derrickcope** [comment] 2018-06-23 03:06
is there any update on this? I am using termite + bspwm + vifm. The image preview works in urxvt but not termite. Has anyone gotten the preview to work with termite + bspwm?

**Comment by Alkeryn** [comment] 2018-06-24 07:18
@derrickcope I think the issue is with bspwm
anyway i switched to st
works well there

**Comment by Moelf** [comment] 2018-07-23 18:22
I'm using sway (wayland i3), urxvt works but termite doesn't with ranger image preview.

**Comment by Alkeryn** [comment] 2018-08-09 11:43
@andrea-82 ofc you won't have the issue you are running i3
the issue only apear when you use 
termite + bspwm
or termite + sway
idk the reason but that's a bug that apear only when both are combined

**Comment by Alkeryn** [comment] 2018-10-11 02:10
@patrick-motard No this dosen't fix anything, because the issue isn't with ranger, but with termite + bspwm combo
you just didn't understood the issue

**Comment by patrick-motard** [comment] 2018-10-11 03:02
@Alkeryn I said explicitly in that commit that I now have previews working using w3m and other users configs found in this issue. At NO POINT did I say that I either understood this issue or had "fixed it" in any way. It's not even a fork. It's a completely different project that is tangentially related. The reference to this issue in MY commit in MY project was to provide breadcrumbs for myself and my projects users as to how I came to the change in that commit.

**Comment by cpadilla** [comment] 2018-11-04 18:20
I'm experiencing this issue as well, only I'm using dwm as my window manager. Image previews work in urxvt but not when I use termite (or st).

I've tried using compton and xcompmgr and even tried it without a composite manager but I can't get it to work in termite. Has there been any update on this issue?

**Comment by oblitum** [comment] 2018-11-16 09:36
This issue may change behavior depending on compositor it seems, I changed from xcompmgr to compton and the behavior changed, now when changing between images, the background of the previous one isn't cleared, so a smaller images appears on top of the last, and this keeps stacking.

**Comment by Pablo1107** [comment] 2018-11-20 23:31
I enable the image preview using w3m but when I preview on an image which is larger than other, the section of the large image stay in the frame bugged until other photo gets on top of it resulting in this look.

https://imgur.com/4JPWHIG

Anyone having this issue?

**Comment by ShayBox** [comment] 2018-11-23 15:42
I don't know where to go with this, is it considered a termite, bspwm, or w3m problem... I guess i would say termite, the program is named after a bug after all :joy: I guess i'll just switch to urxvt in the mean time.

**Comment by Alkeryn** [comment] 2018-12-01 16:31
@ShayBox Both
It only happen when using termite + bspwm
termite + i3 works
urxvt + bspwm works
termite + bspwm don't work

**Comment by Alkeryn** [comment] 2018-12-02 22:30
@ShayBox Yeah what i'd think but the weird thing is that w3m does work on urxvt on bspwm

**Comment by Alkeryn** [comment] 2019-03-02 19:51
I guys, i think you might be interested about a fix i found
i just stoped using w3mimage and i now use ueberzug
and it works even better than w3m
here is an example
![image](https://user-images.githubusercontent.com/11599075/53686842-e157e500-3d2c-11e9-98a2-33d623225d3f.png)
And it can even do full preview and supports resizing : 
![image](https://user-images.githubusercontent.com/11599075/53686847-f2a0f180-3d2c-11e9-8f82-97c275940908.png)

**Comment by lvictorino** [comment] 2019-05-16 20:25
Hey @Alkeryn could you please share your rc.conf please? I can't manager to use ueberzug with ranger. Thanks.

**Comment by Alkeryn** [comment] 2019-05-17 14:05
@lvictorino It isn't in the stable / release ranger version yet, you need to use ranger-git
but here are my dotfiles : 
https://github.com/Alkeryn/dotfiles/tree/master/.config/ranger

**Comment by ifohancroft** [comment] 2019-05-23 18:43
Don't use w3m's image view, use ueberzug instead. It works flawlessly with ranger and Termite.
All you have to do is install a recent version of ranger (so it supports ueberzug - You can check the rc.conf of ranger - if it supports ueberzug - it will be listed in there as one of the supported image preview methods) and ueberzug. Then in rc.conf enable image previews and change the image preview method from w3m to ueberzug. w3mimgdisplay has issues of its own so it may not even be Termite's fault.

P.S. I suggest we close this issue and add an entry in the wiki on here for image previews in Termite with ranger and ueberzug?

**Comment by Alkeryn** [comment] 2019-05-24 04:28
@ifohancroft I already mentioned ueberzug like 3 comments over ^

**Comment by ifohancroft** [comment] 2019-05-24 11:09
@Alkeryn Sorry. I must have missed it.

**Comment by boreq** [comment] 2019-06-06 00:26
I am using the newest ranger and `ueberzug` it is not listed as supported. Neither does it work if set in the config.

**Comment by oblitum** [comment] 2019-06-06 05:15
@boreq many thanks!!! this finally fixes the long standing issue I had with w3m when browsing images and the previously larger browsed image never properly cleared up for displaying the next that simply looked like put on top of the previous.

**Comment by oblitum** [comment] 2019-06-06 05:19
Sadly ranger master is outputting `fatal: not a git repository (or any of the parent directories): .git`message all the time, though seems not harmful...

**Comment by Mishio595** [comment] 2019-06-12 01:36
Even after switching to ueberzug, I'm experiencing this issue. I'm using Sway.
urxvt + w3m -> works
urxvt + ueberzug -> works
termite + w3m -> no preview
termite + ueberzug -> no preview

__Versions__
ranger - master (pulled from git today)
python - 3.7.3
ueberzug - 18.1.3
termite - v15

**Comment by Alkeryn** [comment] 2019-06-12 03:29
@Mishio595 ueberzug can't work in wayland
w3m can't work in termite most of the time

**Comment by Mishio595** [comment] 2019-06-12 05:13
Well, I figured I would try it seeing as termite is the emulator sway recommends and this thread relates to my issue. Disappointing that the only thing close to a solution or workaround anyone has suggested only works under X11.

**Comment by benesposito** [comment] 2019-08-06 05:15
@Mishio595 Did you every find a solution? I am also on Sway and urxvt+w3m works but I use Termite which doesn't work with w3m or ueberzug.

**Comment by Mishio595** [comment] 2019-08-06 08:12
@benesposito I looked for a solution for a while, but everything came up dry. The issue is that both w3m and ueberzug depend on an X server, so native Wayland clients aren't able to utilise them. URxvt runs in Wayland using Xwayland, so it's able to render the images just fime. Until a Wayland-native solution is made, we're basically out of luck.

**Comment by oblitum** [comment] 2019-08-06 14:55
Notice that currently on Arch at least python-ueberzug is broken by default because python-pillow-simd causes it to segfault on many images, I had remove python-ueberzug and python-pillow-simd and install python-ueberzug-nosimd-git instead, that just depends on python-pillow.

**Comment by benesposito** [comment] 2019-08-07 02:48
@Mishio595 Thanks for getting back to me so that I don't also have to waste my time. Hopefully something comes out soon, and if not, I may have to look into it.

**Comment by gcantieni** [comment] 2019-08-14 04:42
Thanks @oblitum that was  the final fix! So now the process on Arch is:

- install `ranger-git`
- install `python-ueberzug-nosimd-git`
- if necessary uninstall `python-pillow-simd` and overwrite it with `python pillow`
- set ranger's rendering method to ueberzug (it should be in the default config comments if you have the right version)

**Comment by thestinger** [comment] 2021-05-07 11:56
Termite is obsolete. Please use [Alacritty](https://github.com/alacritty/alacritty) instead. See https://github.com/thestinger/termite#termite-is-obsoleted-by-alacritty for more details.

**Closed by thestinger** 2021-05-07 11:56 UTC
