### ISSUE TITLE
Support "include" in configuration file

### ISSUE THREAD

**Issue by ghost** [thestinger/termite#260] opened 2015-09-30 19:54 UTC
It would be nice if there was a support for "include" directive in termite's configuration file. This would allow to (optionally) have split configuration files.

This would allow having things such as separate color configuration files (or "themes").

Let me know what you think regarding this.

**Comment by polyzen** [comment] 2015-09-30 22:13
@edvinasme, currently I use separate "themes" via completely separate config files.  How would you specify which theme to use?

**Comment by edvinasme** [comment] 2015-10-01 17:00
> Currently I use separate "themes" via completely separate config files.

How do you merge those files together?

> How would you specify which theme to use?

I want "include" directive to include another file. This way we could split config into 2 files. Examples:

`~/.config/termite/config`:
```
[options]
font = Monaco 9

include = ~/.config/termite/colors
```

`~/.config/termite/colors`:
```
[colors]                                     
foreground = #839496
foreground_bold = #eee8d5
```

This would essentially be the same as having one configuration file with contents:

```
[options]
font = Monaco 9

[colors]                                     
foreground = #839496
foreground_bold = #eee8d5
```

If the `include` directive would look in path relative to the `~/.config/termite/config` file, then we should be able to use this instead:

```
[options]
font = Monaco 9
include = colors <-- this would be the same as ~/.config/termite/colors
```

Let me know if that cleared things up.

**Comment by polyzen** [comment] 2015-10-01 21:09
Common settings I rarely modify are kept in-sync with `vimdiff`.

I have these bindings in my i3 config (will move them to sxhkd eventually):

    #During daylight
    bindsym Mod4+Return exec termite -c .config/termite/config-gruvbox-light

    #After-dark
    bindsym Mod4+Shift+Return exec termite -c .config/termite/config-gruvbox-dark

**Comment by edvinasme** [comment] 2015-10-01 22:51
It's similar thing that I am trying to accomplish. I just thought of symlinking the `color` configuration automatically during appropriate times of the day to `~/.config/termite/colors`. This way it would be picked up automatically. Otherwise, I have to resort to using `sed` to rewrite the color part of the configuration depending on the time of the day. I believe the symlinking with `include` directive would be a more clean solution.

Let me know what you think about this.

**Comment by polyzen** [comment] 2015-10-02 02:18
Rewriting symlinks/configs every day for this seems messy. Normally I have
all my terminals under a multiplexer; so, I just detach the session, reopen
termite with the dark config, and reattach.

I, too, dream of the day when switching between light/dark colorschemes
will be automatic. Going from application-to-application (termite, vim,
firefox [stylish, pentadactyl], can't think of anything else..} and "making
them dark" everyday is a bit annoying :p. There is Redshift, but I'm not
too keen on ..the whole red thing.

**Comment by eigengrau** [comment] 2015-10-21 08:31
Dupe of #43? (Would also love to see this)

**Comment by thestinger** [comment] 2016-02-11 15:57
Not interested in supporting this. More flexible configuration, sure, but not like this.

**Closed by thestinger** 2016-02-11 15:57 UTC
Labels: enhancement

**Comment by marcospb19** [comment] 2020-05-03 21:44
This would be really helpful for creating theme tools.

I'm having trouble with it, it's sad, this seems really simple, when `include` or `source` keyword is detected, termite inserts the file content where the cursor is and continue reading.

**Comment by marcospb19** [comment] 2020-05-04 20:53
I made a [fork](https://github.com/marcospb19/termite) for this issue.
